# Example Configuration File
# Make sure your configuration file is named "config.yml" and resides in root folder of script

# List of YAML manifest files to parse and convert into Steam ROM Manager-compatible json manifests
manifests:
  - ./manifests/some-manifest.yml

output:
  path: ./out
  file: $NAME$.manifest.json
  # Unimplemented; Should output files be minified?
  minify: true
  # Unimplemented; If not minified, how many space characters should be used to indent output files?
  indentation-spaces: 2
  # Unimplemented; Should one source equal one output file or should each entry within the source be its own manifest file?
  # Default: combined   Options: combined, individual
  mode: combined